# Generated by Django 5.1.4 on 2025-01-08 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporteduserspam',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=15),
        ),
    ]
